In [4]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import numpy as np

In [6]:
# Here output (2,3) means 2 is rows and 3 is columns
a = np.array([[1,2,3], 
             [4,5,6]])
a.shape

(2, 3)

why do we need numpy arrays 
numpy arrays is facilitate advanced mathematical and other types of  operations on large numbers of data Typcally such operations are executed 
more effcicient and with less code  than is possible using pythons built in sequences

At the core of numpy package is ndarray object  The encapsulates n-dimnesional arrays of homogeneous data types numpy gives best of both worlds element by element
are operations are default mode is wwhen an ndarray is involved but the element by element operation is speedly executed by pre-complied code in numpy
numpy is very afficient whenever advanced mathematical operations on large data two features is there vectorziation and boardcasting

vectorziation and boardcasting 
vectorziation describes the absence of any explicit and indexing etc behind the scenes in optimized pre-complied code advantages easier to read 
and few lines of code generally means fewer bugs with out vectorziation our code its diffcult to read for loops
while 
boardcasting is describe the element by element behavior operations

In [7]:
# Array Fundamentals
# one dimensional array and two dimensional array ,three dimensional array like set of tables and shapes fundamental array is called ndarray 
# array refer to instance ndarray
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [8]:
a[0]

np.int64(1)


Numpy are started indexed 0 first element array accessed using index 0 not 1

In [9]:
a[4] =50
a

array([ 1,  2,  3,  4, 50,  6])

In [11]:
a[:3]

array([1, 2, 3])

In [12]:
a[3:]

array([ 4, 50,  6])

In [13]:
# new array using another varaible 
b= a[:2]
b

array([1, 2])

In [14]:
b[1]

np.int64(2)

In [15]:
a[:4]

array([1, 2, 3, 4])

In [16]:
# Two and higher dimensional arrays can be initalized from nested python sequences

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a            

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Array Attributes

In [17]:
# This section covers the ndim, shape, size, and dtype attributes of an array
a.ndim

2

In [18]:
# Dimensional array its refer to a-xis 
# ex:
a = np.array(23)
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  0
shape _ ()
Len of shape _ 0
size_ 1


In [19]:
# a = np.array([1,2,4]) this is one dimension means whatever numbers we can give list it will take one dimension shape it will count one so that why len of shape also 1
# shape 3 and size also three 
# a = np.array([1,2,4]) This is single dimension
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  0
shape _ ()
Len of shape _ 0
size_ 1


In [20]:
# number of elements each dimension if you want another dimension or new dimension you can create like this
a = np.array([[1,2,4],
             [1,2,4]]) 
print('No of dimensions _ ',a.ndim)
# print('shape _',a.shape) 2 rows and three columns
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  2
Len of shape _ 2
size_ 6


This is lot of dimensional array its practice mathematical to refer elements of a matrix by the row index first and the column index second .this happens true two dimensional array 
better mode and column index coming last and row index second last this is generalizes array s with any number of dimensions below sentences
import numpy as np


In [21]:


a = np.array(

    [

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [9, 10, 11]
        ]

    ]

)

print('No of dimensions _ ', a.ndim)
print('shape _ ', a.shape)
print('Len of shape _ ', len(a.shape))
print('size_ ', a.size)

No of dimensions _  3
shape _  (3, 2, 3)
Len of shape _  3
size_  18


0-D refered scalar and 1-D vector and 2-D matrix and N-D tensor

In [22]:
a.dtype

dtype('int64')

creating common basics array


In [23]:
np.zeros(2) # its do creating an array its is filled two elements both of 0,0

array([0., 0.])

In [25]:
# zeros function it will take first one shape and datatype so that why came error
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# here 2 of shape and three of rows and 7 of columns
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [27]:
np.zeros((2,3,7,4)) # 7 rows and 4 columns

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0.

In [28]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [29]:
# Here 6 is shape and 3 is rows and 4 is columns
np.ones((6,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

np zeros and np ones difference is doing its creating array and then it is initalizing all the elements either zeros or ones now sometimes what might its happen 
is we want to create an array but  be say calaulating the values later or we might overwrite each of these elements later so it doesnt make the i want to overhead initalizing all the elements 

if have created paricular size  and array i just say we can put any value on that already there memory location that is empty function


Random its doing its create generated random number for us its initailze the array those random numbers

whatever grabage value or whatever value was persent initializing the elements with anything so its going to be faster than np.Z np.ons np do randoms so 
np.mt is very fast its frequently creating array you are going to override all the elements override

In [30]:
np.empty(3)

array([-1.40444743e+306,  3.18618458e-058,  2.12614031e-314])

In [31]:
np.empty((3,8))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56576041e-307, 1.86921143e-306, 3.22651328e-307,
        1.37959333e-306, 1.60219035e-306],
       [1.33511562e-306, 4.22795270e-307, 1.11260755e-306,
        1.42418444e-306, 1.42417221e-306, 1.37961641e-306,
        1.86921143e-306, 6.89813979e-307],
       [1.15711378e-306, 6.23060065e-307, 6.23060744e-307,
        6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306]])

np.zeros()
Useful when you want an initial array with all values starting at zero.
np.ones()

Creates an array filled with 1.
np.empty()

Creates an array without initializing values.

c = np.empty((2,3))
print(c)

Output may contain random garbage values:
    

np.arange () its help range the values np.arange () and np.linspace two we will use matplotlib

In [34]:
# its gives step size 
array = np.arange(2,15,0.5) 

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [35]:
# its give number of elements space that paritcular range
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [38]:
# By default dtype keyword 
x =np.ones(2,dtype=np.int64)
x

array([1, 1])

In [39]:
# By default dtype keyword 
x =np.zeros(2,dtype=np.int64)
x

array([0, 0])

Sort and concatenate

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# argsort its indirect sort specify a-xis
# here 20 is first index and 30 is second index and 10 is zero index
arr =np.array([10,20,30])
np.argsort(arr)

array([0, 1, 2])

lexsort its indirect stable sorton multiple keys
searchsorted which will find the elements in a sorted array,and
partition which is a partial sort

In [45]:
# its will do in arr first three is less and reminding is bigger that is partition
arr =np.array([23,12,45,68,79,90,96,100])
np.partition(arr,3)

array([ 12,  23,  45,  68,  79,  90,  96, 100])

In [48]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
# np.concatenate((arr1,arr2), axis=0) axis=0 its starting vertically 

array([[1, 2],
       [3, 4],
       [5, 6]])

Reshape arrays

In [67]:
# Reshape its will gives new shape with an array without changing data NumPy reshape()

# reshape() usually does not copy data.
arr1 = np.array([1,2,3,4,5,6])

arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [69]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
a.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])