In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import numpy as np

In [3]:
# Here output (2,3) means 2 is rows and 3 is columns
a = np.array([[1,2,3], 
             [4,5,6]])
a.shape

(2, 3)

why do we need numpy arrays 
numpy arrays is facilitate advanced mathematical and other types of  operations on large numbers of data Typcally such operations are executed 
more effcicient and with less code  than is possible using pythons built in sequences

At the core of numpy package is ndarray object  The encapsulates n-dimnesional arrays of homogeneous data types numpy gives best of both worlds element by element
are operations are default mode is wwhen an ndarray is involved but the element by element operation is speedly executed by pre-complied code in numpy
numpy is very afficient whenever advanced mathematical operations on large data two features is there vectorziation and boardcasting

vectorziation and boardcasting 
vectorziation describes the absence of any explicit and indexing etc behind the scenes in optimized pre-complied code advantages easier to read 
and few lines of code generally means fewer bugs with out vectorziation our code its diffcult to read for loops
while 
boardcasting is describe the element by element behavior operations

In [4]:
# Array Fundamentals
# one dimensional array and two dimensional array ,three dimensional array like set of tables and shapes fundamental array is called ndarray 
# array refer to instance ndarray
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [5]:
a[0]

np.int64(1)


Numpy are started indexed 0 first element array accessed using index 0 not 1

In [6]:
a[4] =50
a

array([ 1,  2,  3,  4, 50,  6])

In [7]:
a[:3]

array([1, 2, 3])

In [8]:
a[3:]

array([ 4, 50,  6])

In [9]:
# new array using another varaible 
b= a[:2]
b

array([1, 2])

In [10]:
b[1]

np.int64(2)

In [11]:
a[:4]

array([1, 2, 3, 4])

In [12]:
# Two and higher dimensional arrays can be initalized from nested python sequences

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a            

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Array Attributes

In [13]:
# This section covers the ndim, shape, size, and dtype attributes of an array
a.ndim

2

In [14]:
# Dimensional array its refer to a-xis 
# ex:
a = np.array(23)
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  0
shape _ ()
Len of shape _ 0
size_ 1


In [15]:
# a = np.array([1,2,4]) this is one dimension means whatever numbers we can give list it will take one dimension shape it will count one so that why len of shape also 1
# shape 3 and size also three 
# a = np.array([1,2,4]) This is single dimension
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  0
shape _ ()
Len of shape _ 0
size_ 1


In [16]:
# number of elements each dimension if you want another dimension or new dimension you can create like this
a = np.array([[1,2,4],
             [1,2,4]]) 
print('No of dimensions _ ',a.ndim)
# print('shape _',a.shape) 2 rows and three columns
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  2
Len of shape _ 2
size_ 6


# This is lot of dimensional array its practice mathematical to refer elements of a matrix by the row index first and the column index second .this happens true two dimensional array 
better mode and column index coming last and row index second last this is generalizes array s with any number of dimensions below sentences
import numpy as np


In [17]:


a = np.array(

    [

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [9, 10, 11]
        ]

    ]

)

print('No of dimensions _ ', a.ndim)
print('shape _ ', a.shape)
print('Len of shape _ ', len(a.shape))
print('size_ ', a.size)

No of dimensions _  3
shape _  (3, 2, 3)
Len of shape _  3
size_  18


0-D refered scalar and 1-D vector and 2-D matrix and N-D tensor

In [18]:
a.dtype

dtype('int64')

creating common basics array


In [19]:
np.zeros(2) # its do creating an array its is filled two elements both of 0,0

array([0., 0.])

In [20]:
# zeros function it will take first one shape and datatype so that why came error
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# here 2 of shape and three of rows and 7 of columns
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [23]:
np.zeros((2,3,7,4)) # 7 rows and 4 columns

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0.

In [24]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [25]:
# Here 6 is shape and 3 is rows and 4 is columns
np.ones((6,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# np zeros and np ones difference is doing its creating array and then it is initalizing all the elements either zeros or ones now sometimes what might its happen 
is we want to create an array but  be say calaulating the values later or we might overwrite each of these elements later so it doesnt make the i want to overhead initalizing all the elements 

# if have created paricular size  and array i just say we can put any value on that already there memory location that is empty function


# Random its doing its create generated random number for us its initailze the array those random numbers

# whatever grabage value or whatever value was persent initializing the elements with anything so its going to be faster than np.Z np.ons np do randoms so 
np.mt is very fast its frequently creating array you are going to override all the elements override

In [26]:
np.empty(3)

array([-1.40444743e+306,  3.18618458e-058,  2.12614031e-314])

In [27]:
np.empty((3,8))

array([[ 0.00000000e+000, -7.60686911e-311,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000]])

np.zeros()
Useful when you want an initial array with all values starting at zero.
np.ones()

Creates an array filled with 1.
np.empty()

Creates an array without initializing values.

c = np.empty((2,3))
print(c)

Output may contain random garbage values:
    

np.arange () its help range the values np.arange () and np.linspace two we will use matplotlib

In [28]:
# its gives step size 
array = np.arange(2,15,0.5) 

In [29]:
# its give number of elements space that paritcular range
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
# By default dtype keyword 
x =np.ones(2,dtype=np.int64)
x

array([1, 1])

In [31]:
# By default dtype keyword 
x =np.zeros(2,dtype=np.int64)
x

array([0, 0])

Sort and concatenate

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# argsort its indirect sort specify a-xis
# here 20 is first index and 30 is second index and 10 is zero index
arr =np.array([10,20,30])
np.argsort(arr)

array([0, 1, 2])

lexsort its indirect stable sorton multiple keys
searchsorted which will find the elements in a sorted array,and
partition which is a partial sort

In [34]:
# its will do in arr first three is less and reminding is bigger that is partition
arr =np.array([23,12,45,68,79,90,96,100])
np.partition(arr,3)

array([ 12,  23,  45,  68,  79,  90,  96, 100])

In [35]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])
# np.concatenate((arr1,arr2), axis=0) axis=0 its starting vertically 

Reshape arrays

In [37]:
# Reshape its will gives new shape with an array without changing data NumPy reshape()

# reshape() usually does not copy data.
arr1 = np.array([1,2,3,4,5,6])

arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [39]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [42]:
# np.reshape(arr,(3,2)) new shape array after first variable is passing after

In [43]:
 # np.reshape(arr,(2,3),order ='F') its showing [0,2,4] its came column convert to the row

Add new axis to arrays 

In [44]:
a =np.array([1,2,3,4,5,6])
a.shape

(6,)

In [45]:
a1 =arr[np.newaxis,:]
a1.shape this newaxis convert row vector 

SyntaxError: invalid syntax (1972433607.py, line 2)

# newaxis array will increase the dimensions of your array by one dimension when used once .This means that 1darray will become 2d array will become 3 darray

In [ ]:
a.ndim

In [ ]:
a1.ndim

In [ ]:
col_vector = a[:,np.newaxis] 
col_vector.shape

# you can expand an array by a inserting a new axis  you want specify postion 

In [ ]:
b =np.expand_dims(a,axis=1)
# b.shape axis1 its exective column vector

In [ ]:
b =np.expand_dims(a,axis=0)
# b.shapeaxis0 its exective row vector

reshape we are not restruction we added new dimensions

Indexing and silcing 

In [ ]:
arr_new = np.array([12,89,25])
arr_new



In [ ]:
arr_new[1:]

In [ ]:
arr_new[2:]

In [ ]:
arr_new[2] its showed last element

In [ ]:
arr_new[3:]

In [ ]:
arr_new[-2]

In [ ]:
arr_new[-2:]

In [ ]:
arr_new[:-1]

# This another way of silcing condition
arr_new1= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_new1<6

In [ ]:
arr_new1[arr_new1<6]

In [ ]:
arr_new2= np.array([[91,24,3,4],[5,68,7,89],[9,10,19,120]])
# arr_new2<6 its given random values 

In [ ]:
arr_new2[arr_new2<6]

In [ ]:
arr_new2[(arr_new2<6) | (arr_new2>89)]

# np.nonzero((arr_new2<6) | (arr_new2>89)) nonzeros gives the indicies like this

# Horizontal ,vertical stack Horizontal split

# vertical and horizontal stacking they are taking two arrays they are stacking vertical and horizontal adjucent each other

In [ ]:
arr = np.array([[1,1,3],
                [2,2,4]])
arr1 = np.array([[3,3,6],
                [4,4,7]])

                

In [ ]:
# np.vstack((arr,arr1))its shows numberof columns in horizontal stack

In [ ]:
x =np.arange(1,25).reshape(2,12)
x

In [ ]:
np.hsplit(x,3)

In [ ]:
# np.hsplit(x,(3,4)) if you want split firth array like this 

In [ ]:
# np.hsplit(x,(3,4,7)) if you want many arrays split that time we use like this

# view and copy if we are creating and spliting array  
view are creating new array object its look same data orginal data shallow copy 

In [ ]:
arr = np.arange(6)

In [ ]:
b= arr

In [ ]:
print(arr)
print(b)

# Here i added value in the b variable then printed both arrays are changed that is shallow copied 
b[2] =10
print(arr)
print(b)

In [ ]:
arr

In [ ]:
b = arr[2:4]
b

In [ ]:
b[1] =20
arr

In [ ]:
# if you modified the data orginal data also changed  copy its copied b only not arr means original data
arr = np.arange(6)
b =arr.copy()
b[1]=20
print(arr)
print(b)

# Basic array operations 

In [ ]:
# Board casting 
a = np.arange(2,10)
b=np.arange(5,15)
print(a)
print(b)

In [ ]:
# a+b this means a and b is not dimension complictable

In [ ]:
a = np.arange(2,10)
b=np.arange(5,13)
print(a)
print(b)
# a+b now its same the shape 

In [ ]:
a-b

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
a.sum()

In [ ]:
a = np.arange(1,10)
b=np.arange(1,10)
print(a)
print(b)
# print(a.sum())This is one d-array

# you can access all the rows that time we use axis =0
you can access all the rows that time we use axis =1 

In [ ]:
a.reshape(3,3)

In [ ]:
a.sum()

In [ ]:
b =a.reshape(3,3)
b.sum(axis=0)

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)
# a.sum(axis=0) this add rows

In [ ]:
# a.sum(axis=1)this add columns 

# MIn,Max,Mean,Std,Prod

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.max(axis=0)

In [ ]:
a.min(axis=1)

In [ ]:
a.prod(axis=1)

In [ ]:
a.mean(axis=1)

In [ ]:
a.std(axis=1)

In [ ]:
# if you want entirely array we can do this 
a.std() 


# Generating Random Numbers

In [ ]:
np.random.randint(2,9, (3,2))

In [ ]:
rng = np.random.default_rng()
rng.integers(5,size=(2,4))

In [ ]:
rng.integers(2,9, (3,2))

# unquie its work removed duplicate values excecute uquie values and Transpose its work for ex one arr 3 shape and two values that convert 2 shape and three values its executed 

In [ ]:
# unquie items transfornming matrix reverse arrays
arr = rng.integers(2,9, (3,2))
arr

In [46]:
# arr.transpose()its not changed the array 

array([0, 1, 2, 3, 4, 5])

In [48]:
arr.T

array([0, 1, 2, 3, 4, 5])

In [51]:
arr_2d =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [52]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [53]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
reversed_arrcolumns = np.flip(arr_2d,axis=1)
print(reversed_arrcolumns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [55]:
# you can reverse the contents rows at index postion 1 (the second row)
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [56]:
# you can reverse the contents rows at index postion 1 (the second column)

In [59]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Flatten means you have multiple dimensions array is there its will work 1darray

In [61]:
a =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# ravel its changes original array

# ravel doesnt create a copy vs Flatten changes new array its wont change  parent array

# Finally here flatten array not change orginal array its change new array only 
a1 =a.flatten()
a1[0] =99
print(a) 
print(a1)


# Finally here ravel array orginal changed new array its changed only 
a2 =a.ravel()
a2[0] =90
print(a) 
print(a2)


In [74]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

