In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd
import numpy as np

In [4]:
# Here output (2,3) means 2 is rows and 3 is columns
a = np.array([[1,2,3], 
             [4,5,6]])
a.shape

(2, 3)

why do we need numpy arrays 
numpy arrays is facilitate advanced mathematical and other types of  operations on large numbers of data Typcally such operations are executed 
more effcicient and with less code  than is possible using pythons built in sequences

At the core of numpy package is ndarray object  The encapsulates n-dimnesional arrays of homogeneous data types numpy gives best of both worlds element by element
are operations are default mode is wwhen an ndarray is involved but the element by element operation is speedly executed by pre-complied code in numpy
numpy is very afficient whenever advanced mathematical operations on large data two features is there vectorziation and boardcasting

vectorziation and boardcasting 
vectorziation describes the absence of any explicit and indexing etc behind the scenes in optimized pre-complied code advantages easier to read 
and few lines of code generally means fewer bugs with out vectorziation our code its diffcult to read for loops
while 
boardcasting is describe the element by element behavior operations

In [5]:
# Array Fundamentals
# one dimensional array and two dimensional array ,three dimensional array like set of tables and shapes fundamental array is called ndarray 
# array refer to instance ndarray
a = np.array([1,2,3,4,5,6])
a


array([1, 2, 3, 4, 5, 6])

In [6]:
a[0]

np.int64(1)


Numpy are started indexed 0 first element array accessed using index 0 not 1

In [7]:
a[4] =50
a

array([ 1,  2,  3,  4, 50,  6])

In [8]:
a[:3]


array([1, 2, 3])

In [9]:
a[3:]

array([ 4, 50,  6])

In [10]:
# new array using another varaible 
b= a[:2]
b

array([1, 2])

In [11]:
b[1]

np.int64(2)

In [12]:
a[:4]

array([1, 2, 3, 4])

In [13]:
# Two and higher dimensional arrays can be initalized from nested python sequences

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a            

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Array Attributes

In [ ]:
# This section covers the ndim, shape, size, and dtype attributes of an array
a.ndim

2

In [16]:
# Dimensional array its refer to a-xis 
# ex:
a = np.array(23)
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  0
shape _ ()
Len of shape _ 0
size_ 1


In [17]:
# a = np.array([1,2,4]) this is one dimension means whatever numbers we can give list it will take one dimension shape it will count one so that why len of shape also 1
# shape 3 and size also three 
# a = np.array([1,2,4]) This is single dimension
print('No of dimensions _ ',a.ndim)
print('shape _',a.shape)
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  1
shape _ (3,)
Len of shape _ 1
size_ 3


In [23]:
# number of elements each dimension if you want another dimension or new dimension you can create like this
a = np.array([[1,2,4],
             [1,2,4]]) 
print('No of dimensions _ ',a.ndim)
# print('shape _',a.shape) 2 rows and three columns
print('Len of shape _',len(a.shape))
print('size_',a.size)

No of dimensions _  2
shape _ (2, 3)
Len of shape _ 2
size_ 6


This is lot of dimensional array its practice mathematical to refer elements of a matrix by the row index first and the column index second .this happens true two dimensional array 
better mode and column index coming last and row index second last this is generalizes array s with any number of dimensions below sentences
import numpy as np


In [35]:


a = np.array(

    [

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [3, 4, 5]
        ],

        [
            [1, 2, 4],
            [9, 10, 11]
        ]

    ]

)

print('No of dimensions _ ', a.ndim)
print('shape _ ', a.shape)
print('Len of shape _ ', len(a.shape))
print('size_ ', a.size)

No of dimensions _  3
shape _  (3, 2, 3)
Len of shape _  3
size_  18


0-D refered scalar and 1-D vector and 2-D matrix and N-D tensor

In [38]:
a.dtype

dtype('int64')

creating common basics array


In [ ]:
np.zeros(2) # its do creating an array its is filled two elements both of 0,0

array([0., 0.])

In [41]:
# zeros function it will take first one shape and datatype so that why came error
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

In [42]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# here 2 of shape and three of rows and 7 of columns
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,7,4)) # 7 rows and 4 columns

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0.

In [45]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [47]:
# Here 6 is shape and 3 is rows and 4 is columns
np.ones((6,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

np zeros and np ones difference is doing its creating array and then it is initalizing all the elements either zeros or ones now sometimes what might its happen 
is we want to create an array but  be say calaulating the values later or we might overwrite each of these elements later so it doesnt make the i want to overhead initalizing all the elements 

if have created paricular size  and array i just say we can put any value on that already there memory location that is empty function


Random its doing its create generated random number for us its initailze the array those random numbers